2019-11-06 09:43:03,258 ERROR: Exception on /register [GET] [in /home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ygreneco/flask_app/app/routes.py", line 159, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ygreneco/flask_app/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 1, in top-level template code
    {% block content %}
  File "/home/ygreneco/flask_app/app/templates/base.html", line 16, in block "content"
    {% block app_content %}
  File "/home/ygreneco/flask_app/app/templates/register.html", line 9, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/ygreneco/virtualenv/flask_app/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2019-11-06 10:00:07,391 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 10:21:45,115 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 10:47:13,367 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 11:22:41,929 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 11:35:24,036 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 12:44:36,146 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 13:06:54,102 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 14:35:32,388 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 15:14:00,789 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 15:37:55,102 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 16:19:03,372 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
2019-11-06 16:39:54,822 INFO: Microblog startup [in /home/ygreneco/flask_app/app/__init__.py:51]
